language: python
python: "3.3"

before_install:
  - sudo apt-get install build-essential python-dev
  - sudo apt-get install libev4 libev-dev

install: pip install tox setuptools virtualenv --upgrade

env:
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pep8

script: tox -v -e $TOX_ENV

notifications:
  email:
    - jamie.painter@rackspace.com
    - xuan.yu@rackspace.com
